# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='haze_PSI_24hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=3)),
                ('timestamp', models.IntegerField()),
                ('reading', models.IntegerField()),
            ],
        ),
    ]
