# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('category', models.IntegerField()),
                ('status', models.IntegerField(choices=[('1', 'Dispatched'), ('0', 'Pending'), ('2', 'Resolved')])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
