# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0005_auto_20170404_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userType',
            field=models.IntegerField(choices=[(1, 'CallOperator'), (2, 'CivilDefense'), (3, 'Police'), (4, 'LTA')], null=True),
        ),
    ]
