# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0006_auto_20170404_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Dispatched'), (2, 'Resolved')]),
        ),
    ]
