# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0007_auto_20170404_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.IntegerField(choices=[(0, 'Fire'), (1, 'TrafficAccient'), (2, 'TerroristAttack')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Resolving'), (2, 'Closed')], default=0),
        ),
    ]
