# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0008_auto_20170408_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=10),
        ),
    ]
