# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0010_auto_20170408_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.IntegerField(choices=[(0, 'Fire'), (1, 'Traffic Accient'), (2, 'Terrorist Attack')]),
        ),
        migrations.AlterField(
            model_name='case',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Call Operator'), (2, 'Civil Defense'), (3, 'Police'), (4, 'LTA')], null=True),
        ),
    ]
