# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0012_auto_20170408_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.IntegerField(choices=[(0, 'Rescue and Emergency'), (1, 'Traffic Accient'), (2, 'Terrorist Attack')]),
        ),
    ]
