# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0013_auto_20170408_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='casualties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='injured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='severity',
            field=models.IntegerField(default=0),
        ),
    ]
