# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0015_auto_20170409_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='place_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
