# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0017_auto_20170409_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
    ]
