# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0020_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.IntegerField(choices=[(0, 'Central Region'), (1, 'North-East Region'), (2, 'North-West Region'), (3, 'South-East Region'), (4, 'South-West Region')]),
        ),
    ]
